baseURL = 'https://kyoungsun.github.io/'
languageCode = 'en-us'
title = 'Librispace Blog'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Welcome to Librispace Blog", Content = "개발 기록을 꾸준히 남기는 공간입니다." }

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

